# Generated by Django 5.0.2 on 2024-03-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_avatar_alter_user_hometown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('member', 'Member'), ('moder', 'Moderator')], default='member', max_length=6, null=True),
        ),
    ]
