# Generated by Django 5.0.2 on 2024-04-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_stripepayment_alter_subscription_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StripePayment',
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='price_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='product_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
